### ISSUE TITLE
Python builds should not set CMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by vyasr** [rapidsai/devcontainers#280]
For Python builds driven by scikit-build-core, the correct way to set the build type is using [scikit-build-core's own variable `SKBUILD_CMAKE_BUILD_TYPE`](https://scikit-build-core.readthedocs.io/en/latest/configuration.html#configuring-cmake-arguments-and-defines). Setting `CMAKE_BUILD_TYPE` directly is not supported. [That argument will be filtered out and it will raise a warning](https://github.com/scikit-build/scikit-build-core/blob/270dee651459256385916d1b947f6f2fa566cee5/src/scikit_build_core/builder/builder.py#L78).

**Comment by trxcllnt** [comment]
Does setting the `CMAKE_ARGS`/`SKBUILD_BUILD_OPTIONS` envvars cause issues for SKBC, or does it simply ignore them?

If it ignores them (and we need to set other envvars which would be ignored by SKB [legacy]), then I think we should define both.

**Comment by vyasr** [comment]
SKBC supports both `CMAKE_ARGS` (space-separated) and `SKBUILD_CMAKE_ARGS` (semicolon-separated). It ignores `SKBUILD_BUILD_OPTIONS`. If you set `CMAKE_BUILD_TYPE` inside `CMAKE_ARGS` it will just ignore it. I assume it also does so for `SKBUILD_CMAKE_ARGS`, but have not checked that case (devcontainers don't use the latter so it's not relevant here anyway AFAIK).

I'm fine with that if you want to continue supporting projects that use SKB in devcontainers. If you plan to do so in perpetuity, it might be nice to filter out the undesired argument based on whether a project is build with SKB or SKBC. If you have a timeline for dropping SKB support, then that's probably not worth it and we can just have the warning show up until SKB support is dropped.

**Comment by trxcllnt** [comment]
Seems like defining it via `SKBUILD_CMAKE_BUILD_TYPE` hides the warning.

I'm disappointed that SKBC stopped supporting `SKBUILD_BUILD_OPTIONS`. How else is someone supposed to pass tool-specific flags? For example, to orchestrate make jobserver settings, or pass `--load`? Seems short-sighted.

**Comment by vyasr** [comment]
Feel free to comment on https://github.com/scikit-build/scikit-build-core/issues/380, which I opened for exactly this. At the time I didn't have specific build options that I wanted, but if you have specific ideas I'm sure the devs would be receptive.
