### ISSUE TITLE
Move to clang-format 18

### ISSUE THREAD

**Issue by bernhardmgruber** [rapidsai/devcontainers#341]
Our CCCL pre-commit [informed us](https://github.com/NVIDIA/cccl/pull/1928) of an available update that includes moving from clang-format 17.0.6 to 18.1.8. @jrhemstad pointed out this needs to be synced with the version installed in the devcontainers, so developers will have a good experience of getting the same formatting locally as what the CI checks for. Hence this issue.

I kindly ask to upgrade the clang-format version to the latest 18 release in devcontainers. We can then fix the pre-commit clang-format version to that version.

**Comment by trxcllnt** [comment]
You can bump the CCCL clang format version by updating [this line](https://github.com/rapidsai/devcontainers/blob/2f216e1a663082248a8d0708af25b0bbbf74f5e7/matrix.yml#L44) in the image matrix.
