### ISSUE TITLE
ninja bash completion is missing

### ISSUE THREAD

**Issue by bernhardmgruber** [rapidsai/devcontainers#362]
I noticed that despite `ninja` being available in `/usr/bin/ninja`, the apt package `ninja-build` is not installed. This package would include the bash completion for ninja, which is available by sourcing `/usr/share/bash-completion/completions/ninja`.

Since bash completion is super useful, I kindly ask to either provide the completion file in the dev containers or install the apt package by default.

**Comment by trxcllnt** [comment]
The devcontainers install ninja from the [github releases](https://github.com/ninja-build/ninja/releases), but we could definitely add the [ninja bash completions](https://github.com/ninja-build/ninja/blob/master/misc/bash-completion) too.

**Comment by bernhardmgruber** [comment]
This would be amazing! You could even source it upon startup for maximum user satisfaction :)

**Comment by trxcllnt** [comment]
Placing it into the bash completions dir will source it automatically.

**Comment by bernhardmgruber** [comment]
Thx a lot! <3
